services:

  rag_chatbot:
    build: .
    container_name: rag_chatbot
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      OLLAMA_HOST: http://ollama:11434
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chatbot 
      DB_USER: chatbot
      DB_PASSWORD: chatbot 
    
    networks:
      - qa_chatbot_default
    volumes:
      - ./research_papers:/app/research_papers
      - ./vector_store:/app/vector_store
      - ./.streamlit:/app/.streamlit


networks:
  qa_chatbot_default:
    external: true